PakPoliticalTrends/urls.py
from django.contrib import admin
from django.urls import path
from  django.conf.urls import include
from Pak_Political_Trends import views

urlpatterns = [
    path('', views.index, name='index'),
    path('Pak_Political_Trends/', include('Pak_Political_Trends.urls')),
    path('admin/', admin.site.urls),
    path('logout/', views.user_logout, name='logout'),
    path('logout/userlogin/', views.user_login, name='userlogin'),
]

Pak_Political_Trends/urls.py
from django.urls import path
from Pak_Political_Trends import views

app_name = 'Pak_Political_Trends'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('trends_form/', views.trends_form, name='trends_form'),
    path('user_registration/', views.user_registration, name='user_registration'),
    path('user_login/', views.user_login, name='user_login'),
    path('user_login/index', views.index, name='index'),
]

Pak_Political_Trends/models.py
from django.db import models
from django.contrib.auth.models import User


class TrendsForm(models.Model):
    topic = models.CharField(max_length=100)
    to_date = models.DateField()
    from_date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.PROTECT)

Pak_Political_Trends/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from Pak_Political_Trends.models import TrendsForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                           'placeholder': 'E-Mail', 'required': True}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Username', 'required': True}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'placeholder': 'First Name', 'required': True}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'placeholder': 'Last Name', 'required': True}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Password', 'required': True}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                  'placeholder': 'Confirm Password', 'required': True}))

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'username',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class TrendsInputForm(forms.Form):
    topic = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                          'placeholder': 'Topic/Politician Name'}))
    to_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control',
                                                            'placeholder': 'Date To e.g. 10/25/06',
                                                            'required': True}))
    from_date = forms.DateField(widget=forms.DateInput(attrs={'class': 'form-control',
                                                              'placeholder': 'Date Form e.g. 10/25/06',
                                                              'required': True}))

    class Meta:
        model = TrendsForm
        fields = (
            'topic',
            'to_date',
            'from_date',
        )

Pak_Political_Trends/views.py
from django.shortcuts import render, redirect
from Pak_Political_Trends.forms import RegistrationForm, TrendsInputForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    return render(request, 'Pak_Political_Trends/index.html')


def about(request):
    return render(request, 'Pak_Political_Trends/about.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('userlogin')


@login_required
def trends_form(request):
    if request.method == 'GET':
        trends_input_form = TrendsInputForm(request.GET)

        if trends_input_form.is_valid():
            return redirect('/Pak_Political_Trends/')
    else:
        trends_input_form = TrendsInputForm()

    return render(request, 'Pak_Political_Trends/trends_form.html', {'trends_input_form': trends_input_form})


def user_registration(request):
    if request.method == 'POST':
        signup_form = RegistrationForm(request.POST)

        if signup_form.is_valid():
            signup_form.save()
            return redirect('/Pak_Political_Trends/')
    else:
        signup_form = RegistrationForm()

    return render(request, 'Pak_Political_Trends/user_registration.html', {'signup_form': signup_form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                if 'next' in request.POST:
                    return HttpResponseRedirect(request.POST.get('next'))
                else:
                    return HttpResponseRedirect('index')

            else:
                HttpResponse("Account Is Not Active")
        else:
            HttpResponse("Invalid Login Credentials")
            return render(request, 'Pak_Political_Trends/userlogin.html')
    else:
        return render(request, 'Pak_Political_Trends/userlogin.html')

templates/Pak_Political_Trends/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>About - Pak Political Trends</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "vendor/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/modern-business.css" %}" rel="stylesheet">

</head>

<body background="{% static "images/Full_Background.png" %}">

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'Pak_Political_Trends:index' %}">Pak Political Trends</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link " href="{% url 'Pak_Political_Trends:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:trends_form' %}">View Trends</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:user_registration' %}">Register</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:user_login' %}">Login</a>
                </li>
                {% endif %}
            <!--
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Other Pages
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                        <a class="dropdown-item" href="">FAQ</a>
                        <a class="dropdown-item" href="">404</a>
                        <a class="dropdown-item" href="">Pricing Table</a>
                    </div>
                </li>
                -->
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">About
        <small>"Pak Political Trends"</small>
    </h1>

    <ol class="breadcrumb" style="background-color: #d5f4e6;">
        <li class="breadcrumb-item">
            <a href="{% url 'Pak_Political_Trends:index' %}">Home</a>
        </li>
        <li class="breadcrumb-item active">About</li>
    </ol>

    <!-- Intro Content -->
    <div class="row">
        <div class="col-lg-6">
            <img class="img-fluid rounded mb-4" src="{% static "images/About us small.png" %}" width="700px" height="450px" >
        </div>
        <div class="col-lg-6">
            <h2>About Us</h2>
            <p>Sentiment analysis is the process of determining the feeling behind a piece of text, conversation or a
                social media update. It has been used on Twitter and other social media channels as a way of judging
                public attitude for many years and 86% of marketers are said to value it highly.<br>

                On Twilert and indeed in Twitter search, it is possible to find tweets obtaining to positive or negative
                sentiment using the search operators :) and :( indicating happiness and unhappiness. This basic type
                of search not only helps you to gain brand feeling and the areas which need improvement, but can also
                help you search out the topics, competitors and services your customers like and dislike!<br> </p>
        </div>
    </div>
    <!-- /.row -->

    <!-- Team Members -->
    <h2>Our Team</h2>

    <div class="row">
        <div class="col-lg-4 mb-4">
            <div class="card h-100 text-center" style="background-color: #E0FFFF;">

                <div class="card-body">
                    <h4 class="card-title">Ali Raza</h4>
                </div>
                <div class="card-footer">
                    <a href="#">raza4729@gmail.com</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4">
            <div class="card h-100 text-center" style="background-color: #E0FFFF;">

                <div class="card-body">
                    <h4 class="card-title">Muhammad Taimoor</h4>
                </div>
                <div class="card-footer">
                    <a href="#">tish997@gmail.com</a>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4">
            <div class="card h-100 text-center" style="background-color: #E0FFFF;">

                <div class="card-body">
                    <h4 class="card-title">Umavia Shaker</h4>
                </div>
                <div class="card-footer">
                    <a href="#">umaviashaker.1995@gmail.com</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->

    <!-- Our Customers -->

    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-2 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright 2017-18 &copy; All Rights Reserved</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

</body>

</html>

templates/Pak_Political_Trends/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Home - Pak Political Trends</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static "vendor/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static "css/modern-business.css" %}" rel="stylesheet">

    <style type="text/css">
        .indexbgimg {
            background-image: url('/static/images/Full_Background.png');
        }
    </style>


</head>

<body background="{% static "images/Full_Background.png" %}">

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'Pak_Political_Trends:index' %}">Pak Political Trends</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Pak_Political_Trends:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Pak_Political_Trends:trends_form' %}">View Trends</a>
        </li>

          {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'Pak_Political_Trends:user_registration' %}">Register</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'Pak_Political_Trends:user_login' %}">Login</a>
              </li>
          {% endif %}
      <!--
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Other Pages
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog2">

            <a class="dropdown-item" href="">FAQ</a>
            <a class="dropdown-item" href="">404</a>
            <a class="dropdown-item" href="">Pricing Table</a>

          </div>
        </li>
        -->
      </ul>
    </div>
  </div>
</nav>


<header>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="width: 100% !important;">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">

      <div class="carousel-item active" style="background-image: url('/static/images/PTI.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h3></h3>
          <p></p>
        </div>
      </div>

      <div class="carousel-item" style="background-image: url('/static/images/PML-N.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h3></h3>
          <p></p>
        </div>
      </div>

      <div class="carousel-item" style="background-image: url('/static/images/PPP_New.jpg')">
        <div class="carousel-caption d-none d-md-block">
          <h3></h3>
          <p></p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</header>

<!-- Page Content -->
<div class="indexbgimg">
<div class="container">

  <h1 class="my-4 text-center">Welcome to Pak Political Trends</h1>

  <!-- Marketing Icons Section -->
  <div class="row">
    <div class="col-lg-4 mb-4">
      <div class="card h-100" style="background-color: #d5f4e6;">
        <h4 class="card-header">What Is Sentiment Analysis ?</h4>
        <div class="card-body" style="background-color: #E0FFFF;">
          <p class="card-text">Sentiment analysis (sometimes known as opinion mining) refers to the use of
            natural language processing, text analysis, computational linguistics, and biometrics to systematically
            identify, extract, quantify, and study affective states ...</p>
        </div>
        <div class="card-footer" style="background-color: #d5f4e6;">
          <a href="#" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4 mb-4">
      <div class="card h-100" style="background-color: #d5f4e6;">
        <h4 class="card-header">Why We Are Using Twitter ??</h4>
        <div class="card-body" style="background-color: #E0FFFF;">
          <p class="card-text">Studies that looked at sentiment analysis of tweets around Hilary Clinton and Donald
            Trump on the recent presidential election in fact showed up much more accurate results obtaining to the
            final result than many of the poles that outrightly ...</p>
        </div>
        <div class="card-footer" style="background-color: #d5f4e6;">
          <a href="#" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
    <div class="col-lg-4 mb-4">
      <div class="card h-100" style="background-color: #d5f4e6;">
        <h4 class="card-header">Worth of Accurate Results ??</h4>
        <div class="card-body" style="background-color: #E0FFFF;">
          <p class="card-text">Final results that are obtained by sentiment analysis are pretty much accurate and you
            can take decision on the basis of that result.</p>
        </div>
        <div class="card-footer" style="background-color: #d5f4e6;">
          <a href="#" class="btn btn-primary">Learn More</a>
        </div>
      </div>
    </div>
  </div>
  <!-- /.row -->

  <!-- Features Section -->
  <div class="row">
    <div class="col-lg-6">
      <h2>Pak Political Trends Premium Services</h2>
      <p>Our Premium Services includes:</p>
      <ul>
        <li>Displays Different Trends about any Topic of Your Choice </li>
        <li>Comparison Between 2 Political Personalities </li>
        <li>Top 5 Cities and States From where most tweets posted </li>
      </ul>
      <p> </p>
    </div>
    <div class="col-lg-6">
      <img class="rounded" src="{% static "images/twitter trends.png" %}" width="480px" height="270px">
    </div>
  </div>
  <!-- /.row -->

  <hr>

</div>

<!-- /.container -->

<!-- Footer -->
<footer class="py-2 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright 2017-18 &copy; All Rights Reserved</p>
  </div>
  <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
</div>
</body>

</html>

templates/Pak_Political_Trends/trends_form.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>View Trends - Pak Political Trends</title>

    <!-- Bootstrap core CSS -->
     <link href="{% static "vendor/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/modern-business.css" %}" rel="stylesheet">


</head>

<body background="{% static "images/Full_Background.png" %}">

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'Pak_Political_Trends:index' %}">Pak Political Trends</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:about' %}">About</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:trends_form' %}">View Trends</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:user_registration' %}">Register</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:user_login' %}">Login</a>
                </li>
                {% endif %}

            <!--
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Other Pages
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                        <a class="dropdown-item" href="">FAQ</a>
                        <a class="dropdown-item" href="">404</a>
                        <a class="dropdown-item" href="">Pricing Table</a>
                    </div>
                </li>
                -->
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">View Trends

    </h1>

    <ol class="breadcrumb" style="background-color: #d5f4e6;">
        <li class="breadcrumb-item">
            <a href="{% url 'Pak_Political_Trends:index' %}">Home</a>
        </li>
        <li class="breadcrumb-item active">View Trends</li>
    </ol>

    <!-- Image Header -->
    <img class="img-fluid rounded mb-4" src="{% static "images/Big Cover Banner.png "%}" alt="">

    <!-- Marketing Icons Section -->

    <div class="row">

        <div class="col-lg-5 mb-3 col-centered custom_pad">
            <div class="card h-100" style="background-color: #d5f4e6;">
                <h4 class="card-header text-center">Please Enter Following Details</h4>
                <div class="card-body" style="background-color: #E0FFFF;">
                    <div class="row w-100 justify-content-lg-center">

                    <form method="get" style="text-align: center; padding-left: 25px">
                        {% csrf_token %}
                        {{ trends_input_form.as_p.non_field_errors }}
                        <div class="fieldWrapper form-group">
                            {{ trends_input_form.topic }}
                        </div>

                        <div class="fieldWrapper form-group">
                            {{ trends_input_form.to_date }}
                        </div>

                        <div class="fieldWrapper form-group">
                            {{ trends_input_form.from_date }}
                        </div>

                        <div class="fieldWrapper form-group">
                            <input class="btn btn-primary btn-danger" type="submit" value="Submit">
                        </div>

                    </form>
                    </div>
                </div>

            </div>
        </div>

    </div>

    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-2 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright 2017-18 &copy; All Rights Reserved</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

</body>
</html>

templates/Pak_Political_Trends/userlogin.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login - Pak Political Trends</title>

    <!-- Bootstrap core CSS -->
     <link href="{% static "vendor/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "css/modern-business.css" %}" rel="stylesheet">


</head>

<body background="{% static "images/Full_Background.png" %}">

<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'Pak_Political_Trends:index' %}">Pak Political Trends</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:trends_form' %}">View Trends</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Pak_Political_Trends:user_registration' %}">Register</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'Pak_Political_Trends:user_login' %}">Login</a>
                </li>
                {% endif %}

            <!--
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Other Pages
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                        <a class="dropdown-item" href="">FAQ</a>
                        <a class="dropdown-item" href="">404</a>
                        <a class="dropdown-item" href="">Pricing Table</a>
                    </div>
                </li>
                -->
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Please Login Here</h1>

    <ol class="breadcrumb" style="background-color: #d5f4e6;">
        <li class="breadcrumb-item">
            <a href="{% url 'Pak_Political_Trends:index' %}">Home</a>
        </li>
        <li class="breadcrumb-item active">Login</li>
    </ol>

    <!-- Image Header -->
    <img class="img-fluid rounded mb-4" src="{% static "images/login_banner.png"%}" style="height: 195px !important; width: 100%">

    <!-- Marketing Icons Section -->

    <div class="row">

        <div class="col-lg-5 mb-4 col-centered">
            <div class="card h-100" style="background-color: #d5f4e6;">
                <h4 class="card-header text-center">Login</h4>
                <div class="card-body" style="background-color: #E0FFFF;">
                    <div class="row w-100 justify-content-lg-center">
                        <form action="{% url 'Pak_Political_Trends:user_login' %}" method="post" style="text-align: center; padding-left: 28px">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username"></label>
                                <input type="text" class="form-control" id="username" name="username"
                                       placeholder="Username" required="required">
                            </div>

                            <div class="form-group">
                                <label for="password"></label>
                                <input type="password" class="form-control" id="password" name="password"
                                       placeholder="Password" required="required">
                            </div>

                            {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                            {% endif %}
                            <div class="form-group">
                                <input class="btn btn-primary btn-danger" type="submit" value="Login">
                            </div>
                        <div class="text-center">
                            <p>Don't Have An Account ?
                                <a href="{% url 'Pak_Political_Trends:user_registration' %}">Click Here</a> </p>
                        </div>

                        </form>
                   </div>
                </div>

            </div>
        </div>

    </div>

    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-2 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright 2017-18 &copy; All Rights Reserved</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

</body>
</html>